import {BASE_URL} from "../../general/global-consts";

export const AUTH_ENDPOINTS = {
    LOGIN: `/auth/login`,
    GET_DATA_ABOUT_CURRENT_ACTIVE_USER: `/auth/me`,
    REG_CONFIRMATION: `/auth/registration-confirmation`,
    REGISTRATION:`/auth/registration`,
    RESEND_REG_CONF_EMAIL: `/auth/registration-email-resending`,
    REFRESH_TOKEN: `/auth/refresh-token`,
    LOGOUT: `/auth/logout`
}

export const AUTH_FULL_URLS = {
    LOGIN: `${BASE_URL}${AUTH_ENDPOINTS.LOGIN}`,
    GET_DATA_ABOUT_CURRENT_ACTIVE_USER: `${BASE_URL}${AUTH_ENDPOINTS.GET_DATA_ABOUT_CURRENT_ACTIVE_USER}`,
    REG_CONFIRMATION: `${BASE_URL}${AUTH_ENDPOINTS.REG_CONFIRMATION}`,
    REGISTRATION: `${BASE_URL}${AUTH_ENDPOINTS.REGISTRATION}`,
    RESEND_REG_CONF_EMAIL: `${BASE_URL}${AUTH_ENDPOINTS.RESEND_REG_CONF_EMAIL}`,
    REFRESH_TOKEN: `${BASE_URL}${AUTH_ENDPOINTS.REFRESH_TOKEN}`,
    LOGOUT: `${BASE_URL}${AUTH_ENDPOINTS.LOGOUT}`,
};